# Generated by Django 3.1.2 on 2020-10-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(blank=True, null=True, verbose_name='City or Town')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Location')),
                ('county', models.TextField(blank=True, null=True, verbose_name='County')),
                ('state', models.TextField(blank=True, null=True, verbose_name='State or Territory')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('estimate_low', models.IntegerField(blank=True, null=True, verbose_name='Attendance Low Estimate')),
                ('estimate_best', models.IntegerField(blank=True, null=True, verbose_name='Attendance Best Estimate')),
                ('estimate_high', models.IntegerField(blank=True, null=True, verbose_name='Attendance High Estimate')),
                ('adjusted_low', models.IntegerField(blank=True, null=True, verbose_name='Adjusted Attendance Low')),
                ('adjusted_high', models.IntegerField(blank=True, null=True, verbose_name='Adjusted Attendance High')),
                ('actor', models.TextField(blank=True, null=True, verbose_name='Actor')),
                ('claim', models.TextField(blank=True, null=True, verbose_name='Claim')),
                ('event_type', models.TextField(blank=True, null=True, verbose_name='Event Type')),
                ('reported_arrests', models.IntegerField(blank=True, null=True, verbose_name='Reported Arrests')),
                ('reported_participant_injuries', models.IntegerField(blank=True, null=True, verbose_name='Reported Participant Injuries')),
                ('reported_police_injuries', models.IntegerField(blank=True, null=True, verbose_name='Reported Police Injuries')),
                ('reported_property_damage', models.IntegerField(blank=True, null=True, verbose_name='Reported Property Damage')),
                ('sources', models.TextField(blank=True, null=True, verbose_name='Array of Sources in JSON Format')),
            ],
        ),
    ]
